`timescale 1ns / 1ps
/*==================================================================================
 File Name:    mem_256x16.v
 Designer:     Michael Marin
 Email:        michaelmarin81@gmail.com
 Rev. Date:    May 10,2017

 Purpose:      This is the memory module of the project. Its purpose to instantiate
               the memory generated by the coregen.
==================================================================================*/
module mem_256x16(clk, we, adr, d_in, d_out);
   input             clk, we ;
   input    [15:0]   adr, d_in ;
   output   [15:0]   d_out ;
   
   memory_256_16 mem_ (
                 .clka(clk), // input clka
                 .wea(we), // input [0 : 0] wea
                 .addra(adr), // input [7 : 0] addra
                 .dina(d_in), // input [15 : 0] dina
                 .douta(d_out) // output [15 : 0] douta
               );
endmodule
